### PR TITLE
Translate for English (U.S.)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by yucheng918** [comment]
I will port more Chinese text in code to i18n/zh_tw.json. Waiting for me to commit the new zh_tw.json to the react-launcher branch.

**Comment by yucheng918** [comment]
I have already committed the complete zh_TW.json

**Comment by ghost** [comment]
Looks like I got work to do. Will do later.

**Comment by ghost** [comment]
Starting now, may be done in a couple hours or more. 

It looks like I'll need to add Linux for the global path file, as it saying unknown OS.
This is being tested on Zorin OS 16 (Ubuntu).

**Pull request closed without merging**
